#Libraries
from PyQt5 import QtCore, QtGui, QtWidgets
import requests
import time
from datetime import date, datetime

#Base Structure
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(883, 600)
        MainWindow.setStyleSheet("background-color: rgb(78, 164, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background_label = QtWidgets.QLabel(self.centralwidget)
        self.background_label.setGeometry(QtCore.QRect(0, 0, 881, 591))
        self.background_label.setText("")
        self.background_label.setPixmap(QtGui.QPixmap("DV9cIm.jpg"))
        self.background_label.setObjectName("background_label")
        self.weatherlogo_label = QtWidgets.QLabel(self.centralwidget)
        self.weatherlogo_label.setGeometry(QtCore.QRect(0, 0, 181, 151))
        self.weatherlogo_label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.weatherlogo_label.setText("")
        self.weatherlogo_label.setPixmap(QtGui.QPixmap("download.jpg"))
        self.weatherlogo_label.setObjectName("weatherlogo_label")
        self.cityname_label = QtWidgets.QLabel(self.centralwidget)
        self.cityname_label.setGeometry(QtCore.QRect(190, 22, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.cityname_label.setFont(font)
        self.cityname_label.setStyleSheet("background-color: rgb(8, 8, 8);\n"
"color: rgb(252, 255, 39);\n"
"")
        self.cityname_label.setObjectName("cityname_label")
        self.cityname_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.cityname_lineEdit.setGeometry(QtCore.QRect(340, 22, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.cityname_lineEdit.setFont(font)
        self.cityname_lineEdit.setStyleSheet("background-color: rgb(203, 203, 255);\n"
"color: rgb(255, 170, 0);\n"
"border-radius: 10px;")
        self.cityname_lineEdit.setFrame(False)
        self.cityname_lineEdit.setObjectName("cityname_lineEdit")
        self.search_pushButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.get_weatherinfo())
        self.search_pushButton.setGeometry(QtCore.QRect(640, 22, 61, 41))
        self.search_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.search_pushButton.setStyleSheet("background-color: rgb(203, 203, 255);\n"
"\n"
"border-radius: 10px;")
        self.search_pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icons/icons/search-icon-without-background.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_pushButton.setIcon(icon)
        self.search_pushButton.setIconSize(QtCore.QSize(36, 38))
        self.search_pushButton.setObjectName("search_pushButton")
        self.mintemp_label = QtWidgets.QLabel(self.centralwidget)
        self.mintemp_label.setGeometry(QtCore.QRect(720, 10, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.mintemp_label.setFont(font)
        self.mintemp_label.setStyleSheet("background-color: rgb(125, 170, 89);\n"
"color: rgb(225, 236, 127);\n"
"border-radius: 15px;")
        self.mintemp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.mintemp_label.setObjectName("mintemp_label")
        self.maxtemp_label = QtWidgets.QLabel(self.centralwidget)
        self.maxtemp_label.setGeometry(QtCore.QRect(720, 80, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.maxtemp_label.setFont(font)
        self.maxtemp_label.setStyleSheet("background-color: rgb(125, 170, 89);\n"
"color: rgb(225, 236, 127);\n"
"border-radius: 15px;")
        self.maxtemp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.maxtemp_label.setObjectName("maxtemp_label")
        self.info_label = QtWidgets.QLabel(self.centralwidget)
        self.info_label.setGeometry(QtCore.QRect(30, 150, 841, 121))
        self.info_label.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 127);")
        self.info_label.setText("")
        self.info_label.setObjectName("info_label")
        self.time_label = QtWidgets.QLabel(self.centralwidget)
        self.time_label.setGeometry(QtCore.QRect(119, 180, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.time_label.setFont(font)
        self.time_label.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(255, 255, 127);\n"
"color: rgb(0, 0, 0);")
        self.time_label.setObjectName("time_label")
        self.day_label = QtWidgets.QLabel(self.centralwidget)
        self.day_label.setGeometry(QtCore.QRect(371, 180, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.day_label.setFont(font)
        self.day_label.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(255, 255, 127);\n"
"color: rgb(0, 0, 0);")
        self.day_label.setObjectName("day_label")
        self.date_label = QtWidgets.QLabel(self.centralwidget)
        self.date_label.setGeometry(QtCore.QRect(633, 180, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.date_label.setFont(font)
        self.date_label.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(255, 255, 127);\n"
"color: rgb(0, 0, 0);")
        self.date_label.setObjectName("date_label")
        self.timeshow_label = QtWidgets.QLabel(self.centralwidget)
        self.timeshow_label.setGeometry(QtCore.QRect(181, 180, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.timeshow_label.setFont(font)
        self.timeshow_label.setStyleSheet("background-color: rgb(70, 150, 255);\n"
"color: rgb(223, 209, 9);\n"
"border-radius:15px;")
        self.timeshow_label.setText("")
        self.timeshow_label.setAlignment(QtCore.Qt.AlignCenter)
        self.timeshow_label.setObjectName("timeshow_label")
        self.dayshow_label = QtWidgets.QLabel(self.centralwidget)
        self.dayshow_label.setGeometry(QtCore.QRect(435, 180, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.dayshow_label.setFont(font)
        self.dayshow_label.setStyleSheet("background-color: rgb(70, 150, 255);\n"
"color: rgb(223, 209, 9);\n"
"border-radius:15px;")
        self.dayshow_label.setText("")
        self.dayshow_label.setAlignment(QtCore.Qt.AlignCenter)
        self.dayshow_label.setObjectName("dayshow_label")
        self.dateshow_label = QtWidgets.QLabel(self.centralwidget)
        self.dateshow_label.setGeometry(QtCore.QRect(697, 180, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.dateshow_label.setFont(font)
        self.dateshow_label.setStyleSheet("background-color: rgb(70, 150, 255);\n"
"color: rgb(223, 209, 9);\n"
"border-radius:15px;")
        self.dateshow_label.setText("")
        self.dateshow_label.setAlignment(QtCore.Qt.AlignCenter)
        self.dateshow_label.setObjectName("dateshow_label")
        self.currenttime1_label = QtWidgets.QLabel(self.centralwidget)
        self.currenttime1_label.setGeometry(QtCore.QRect(40, 150, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.currenttime1_label.setFont(font)
        self.currenttime1_label.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(255, 255, 127);\n"
"color: rgb(134, 138, 124);")
        self.currenttime1_label.setObjectName("currenttime1_label")
        self.currenttime1_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.currenttime1_label_2.setGeometry(QtCore.QRect(40, 180, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.currenttime1_label_2.setFont(font)
        self.currenttime1_label_2.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(255, 255, 127);\n"
"color: rgb(134, 138, 124);")
        self.currenttime1_label_2.setObjectName("currenttime1_label_2")
        self.currenttime1_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.currenttime1_label_3.setGeometry(QtCore.QRect(40, 230, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.currenttime1_label_3.setFont(font)
        self.currenttime1_label_3.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(255, 255, 127);\n"
"color: rgb(134, 138, 124);")
        self.currenttime1_label_3.setObjectName("currenttime1_label_3")
        self.currenttime1_label_4 = QtWidgets.QLabel(self.centralwidget)
        self.currenttime1_label_4.setGeometry(QtCore.QRect(40, 210, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.currenttime1_label_4.setFont(font)
        self.currenttime1_label_4.setStyleSheet("border-radius:15px;\n"
"background-color: rgb(255, 255, 127);\n"
"color: rgb(134, 138, 124);")
        self.currenttime1_label_4.setObjectName("currenttime1_label_4")
        self.temp_label = QtWidgets.QLabel(self.centralwidget)
        self.temp_label.setGeometry(QtCore.QRect(190, 80, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.temp_label.setFont(font)
        self.temp_label.setStyleSheet("background-color: rgb(246, 255, 70);\n"
"color: rgb(7, 7, 7);\n"
"border-radius: 15px;")
        self.temp_label.setText("")
        self.temp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_label.setObjectName("temp_label")
        self.description_label = QtWidgets.QLabel(self.centralwidget)
        self.description_label.setGeometry(QtCore.QRect(340, 80, 361, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.description_label.setFont(font)
        self.description_label.setStyleSheet("background-color: rgb(89, 89, 89);\n"
"color: rgb(255, 255, 127);\n"
"border-radius:15px;")
        self.description_label.setAlignment(QtCore.Qt.AlignCenter)
        self.description_label.setObjectName("description_label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(180, 70, 531, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(710, 1, 3, 148))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(180, 1, 3, 148))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(30, 280, 839, 3))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(60, 330, 381, 191))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tempreture_pushButton = QtWidgets.QPushButton(self.frame)
        self.tempreture_pushButton.setGeometry(QtCore.QRect(10, 10, 61, 51))
        self.tempreture_pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:15px;")
        self.tempreture_pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/icons/icons/tempere.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tempreture_pushButton.setIcon(icon1)
        self.tempreture_pushButton.setIconSize(QtCore.QSize(44, 46))
        self.tempreture_pushButton.setObjectName("tempreture_pushButton")
        self.pressure_pushButton = QtWidgets.QPushButton(self.frame)
        self.pressure_pushButton.setGeometry(QtCore.QRect(10, 75, 61, 51))
        self.pressure_pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:15px;")
        self.pressure_pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/icons/icons/pressure-icon-png-13.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pressure_pushButton.setIcon(icon2)
        self.pressure_pushButton.setIconSize(QtCore.QSize(40, 35))
        self.pressure_pushButton.setObjectName("pressure_pushButton")
        self.humidity_pushButton = QtWidgets.QPushButton(self.frame)
        self.humidity_pushButton.setGeometry(QtCore.QRect(10, 140, 61, 51))
        self.humidity_pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:15px;")
        self.humidity_pushButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/icons/icons/humidity.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.humidity_pushButton.setIcon(icon3)
        self.humidity_pushButton.setIconSize(QtCore.QSize(35, 31))
        self.humidity_pushButton.setObjectName("humidity_pushButton")
        self.tempreture_label = QtWidgets.QLabel(self.frame)
        self.tempreture_label.setGeometry(QtCore.QRect(73, 22, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.tempreture_label.setFont(font)
        self.tempreture_label.setStyleSheet("\n"
"color: rgb(67, 67, 67);\n"
"border-radius:15px;")
        self.tempreture_label.setAlignment(QtCore.Qt.AlignCenter)
        self.tempreture_label.setObjectName("tempreture_label")
        self.pressure_label = QtWidgets.QLabel(self.frame)
        self.pressure_label.setGeometry(QtCore.QRect(73, 85, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.pressure_label.setFont(font)
        self.pressure_label.setStyleSheet("\n"
"color: rgb(67, 67, 67);\n"
"border-radius:15px;")
        self.pressure_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pressure_label.setObjectName("pressure_label")
        self.humidity_label = QtWidgets.QLabel(self.frame)
        self.humidity_label.setGeometry(QtCore.QRect(71, 150, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.humidity_label.setFont(font)
        self.humidity_label.setStyleSheet("\n"
"color: rgb(67, 67, 67);\n"
"border-radius:15px;")
        self.humidity_label.setAlignment(QtCore.Qt.AlignCenter)
        self.humidity_label.setObjectName("humidity_label")
        self.tempshow_label = QtWidgets.QLabel(self.frame)
        self.tempshow_label.setGeometry(QtCore.QRect(210, 23, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.tempshow_label.setFont(font)
        self.tempshow_label.setStyleSheet("background-color: rgb(255, 170, 189);\n"
"color: rgb(67, 67, 67);\n"
"border-radius:15px;")
        self.tempshow_label.setText("")
        self.tempshow_label.setAlignment(QtCore.Qt.AlignCenter)
        self.tempshow_label.setObjectName("tempshow_label")
        self.pressureshow_label = QtWidgets.QLabel(self.frame)
        self.pressureshow_label.setGeometry(QtCore.QRect(210, 86, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.pressureshow_label.setFont(font)
        self.pressureshow_label.setStyleSheet("background-color: rgb(255, 170, 189);\n"
"color: rgb(67, 67, 67);\n"
"border-radius:15px;")
        self.pressureshow_label.setText("")
        self.pressureshow_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pressureshow_label.setObjectName("pressureshow_label")
        self.humidityshow_label = QtWidgets.QLabel(self.frame)
        self.humidityshow_label.setGeometry(QtCore.QRect(210, 149, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.humidityshow_label.setFont(font)
        self.humidityshow_label.setStyleSheet("background-color: rgb(255, 170, 189);\n"
"color: rgb(67, 67, 67);\n"
"border-radius:15px;")
        self.humidityshow_label.setText("")
        self.humidityshow_label.setAlignment(QtCore.Qt.AlignCenter)
        self.humidityshow_label.setObjectName("humidityshow_label")
        self.currentweather_label = QtWidgets.QLabel(self.centralwidget)
        self.currentweather_label.setGeometry(QtCore.QRect(330, 290, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.currentweather_label.setFont(font)
        self.currentweather_label.setStyleSheet("background-color: rgb(89, 89, 89);\n"
"color: rgb(255, 255, 127);\n"
"border-radius:15px;")
        self.currentweather_label.setAlignment(QtCore.Qt.AlignCenter)
        self.currentweather_label.setObjectName("currentweather_label")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(470, 330, 381, 191))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.sindspeed_label = QtWidgets.QLabel(self.frame_2)
        self.sindspeed_label.setGeometry(QtCore.QRect(82, 22, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.sindspeed_label.setFont(font)
        self.sindspeed_label.setStyleSheet("\n"
"color: rgb(67, 67, 67);\n"
"border-radius:15px;")
        self.sindspeed_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sindspeed_label.setObjectName("sindspeed_label")
        self.windspped_pushButton = QtWidgets.QPushButton(self.frame_2)
        self.windspped_pushButton.setGeometry(QtCore.QRect(19, 10, 61, 51))
        self.windspped_pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:15px;")
        self.windspped_pushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/icons/icons/wind speed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.windspped_pushButton.setIcon(icon4)
        self.windspped_pushButton.setIconSize(QtCore.QSize(35, 29))
        self.windspped_pushButton.setObjectName("windspped_pushButton")
        self.sunset_pushButton = QtWidgets.QPushButton(self.frame_2)
        self.sunset_pushButton.setGeometry(QtCore.QRect(19, 140, 61, 51))
        self.sunset_pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:15px;")
        self.sunset_pushButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/icons/icons/sunset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sunset_pushButton.setIcon(icon5)
        self.sunset_pushButton.setIconSize(QtCore.QSize(39, 39))
        self.sunset_pushButton.setObjectName("sunset_pushButton")
        self.sunset_label = QtWidgets.QLabel(self.frame_2)
        self.sunset_label.setGeometry(QtCore.QRect(80, 150, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.sunset_label.setFont(font)
        self.sunset_label.setStyleSheet("\n"
"color: rgb(67, 67, 67);\n"
"border-radius:15px;")
        self.sunset_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sunset_label.setObjectName("sunset_label")
        self.sunrise_pushButton = QtWidgets.QPushButton(self.frame_2)
        self.sunrise_pushButton.setGeometry(QtCore.QRect(19, 75, 61, 51))
        self.sunrise_pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:15px;")
        self.sunrise_pushButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/icons/icons/sunrise.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sunrise_pushButton.setIcon(icon6)
        self.sunrise_pushButton.setIconSize(QtCore.QSize(36, 45))
        self.sunrise_pushButton.setObjectName("sunrise_pushButton")
        self.sunrise_label = QtWidgets.QLabel(self.frame_2)
        self.sunrise_label.setGeometry(QtCore.QRect(82, 85, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.sunrise_label.setFont(font)
        self.sunrise_label.setStyleSheet("\n"
"color: rgb(67, 67, 67);\n"
"border-radius:15px;")
        self.sunrise_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sunrise_label.setObjectName("sunrise_label")
        self.windshow_label = QtWidgets.QLabel(self.frame_2)
        self.windshow_label.setGeometry(QtCore.QRect(210, 20, 170, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.windshow_label.setFont(font)
        self.windshow_label.setStyleSheet("background-color: rgb(255, 170, 189);\n"
"color: rgb(67, 67, 67);\n"
"border-radius:15px;")
        self.windshow_label.setText("")
        self.windshow_label.setAlignment(QtCore.Qt.AlignCenter)
        self.windshow_label.setObjectName("windshow_label")
        self.sunriseshow_label = QtWidgets.QLabel(self.frame_2)
        self.sunriseshow_label.setGeometry(QtCore.QRect(193, 85, 186, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.sunriseshow_label.setFont(font)
        self.sunriseshow_label.setStyleSheet("background-color: rgb(255, 170, 189);\n"
"color: rgb(67, 67, 67);\n"
"border-radius:15px;")
        self.sunriseshow_label.setText("")
        self.sunriseshow_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sunriseshow_label.setObjectName("sunriseshow_label")
        self.sunsetshow_label = QtWidgets.QLabel(self.frame_2)
        self.sunsetshow_label.setGeometry(QtCore.QRect(193, 150, 186, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.sunsetshow_label.setFont(font)
        self.sunsetshow_label.setStyleSheet("background-color: rgb(255, 170, 189);\n"
"color: rgb(67, 67, 67);\n"
"border-radius:15px;")
        self.sunsetshow_label.setText("")
        self.sunsetshow_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sunsetshow_label.setObjectName("sunsetshow_label")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(60, 520, 791, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.visibility_label = QtWidgets.QLabel(self.centralwidget)
        self.visibility_label.setGeometry(QtCore.QRect(30, 540, 210, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.visibility_label.setFont(font)
        self.visibility_label.setStyleSheet("background-color: rgb(255, 170, 189);\n"
"color: rgb(67, 67, 67);\n"
"border-radius:15px;")
        self.visibility_label.setAlignment(QtCore.Qt.AlignCenter)
        self.visibility_label.setObjectName("visibility_label")
        self.feelslike_label = QtWidgets.QLabel(self.centralwidget)
        self.feelslike_label.setGeometry(QtCore.QRect(240, 540, 210, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.feelslike_label.setFont(font)
        self.feelslike_label.setStyleSheet("background-color: rgb(255, 170, 189);\n"
"color: rgb(67, 67, 67);\n"
"border-radius:15px;")
        self.feelslike_label.setAlignment(QtCore.Qt.AlignCenter)
        self.feelslike_label.setObjectName("feelslike_label")
        self.lat_label = QtWidgets.QLabel(self.centralwidget)
        self.lat_label.setGeometry(QtCore.QRect(450, 540, 210, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.lat_label.setFont(font)
        self.lat_label.setStyleSheet("background-color: rgb(255, 170, 189);\n"
"color: rgb(67, 67, 67);\n"
"border-radius:15px;")
        self.lat_label.setAlignment(QtCore.Qt.AlignCenter)
        self.lat_label.setObjectName("lat_label")
        self.lon_label = QtWidgets.QLabel(self.centralwidget)
        self.lon_label.setGeometry(QtCore.QRect(660, 540, 210, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(11)
        self.lon_label.setFont(font)
        self.lon_label.setStyleSheet("background-color: rgb(255, 170, 189);\n"
"color: rgb(67, 67, 67);\n"
"border-radius:15px;")
        self.lon_label.setAlignment(QtCore.Qt.AlignCenter)
        self.lon_label.setObjectName("lon_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def get_weatherinfo(self):
        current_time = datetime.now().strftime("%H:%M:%S %p")
        self.timeshow_label.setText(f'{current_time}')
        today_day_name = date.today().strftime("%A")
        self.dayshow_label.setText(f'{today_day_name}')
        today_date = date.today().strftime("%Y:%B:%d")
        self.dateshow_label.setText(f'{today_date}')

        city = self.cityname_lineEdit.text()
        API = '1faca6c868d5cd0cee580f66fc761775'
        URL = f'https://api.openweathermap.org/data/2.5/weather?q={city}&appid={API}&units=metric'
        r = requests.get(URL)
        res = r.json()
        print(res)
        
        temp = res['main']['temp']
        temp_min = res['main']['temp_min']
        temp_max = res['main']['temp_max']
        pressure = res['main']['pressure']
        humidity = res['main']['humidity']
        wind_speed = res['wind']['speed']
        sunrise = datetime.fromtimestamp(res['sys']['sunrise'])
        sunset = datetime.fromtimestamp(res['sys']['sunset'])
        description = res['weather'][0]['description']
        visibility = res['visibility']
        feels_like = res['main']['feels_like']
        lat_coord = res['coord']['lat']
        lon_coord = res['coord']['lon']
        

        self.temp_label.setText(f'{temp} c')
        self.mintemp_label.setText(f'{temp_min} c')
        self.maxtemp_label.setText(f'{temp_max} c')
        self.description_label.setText(f'{description}')
        self.tempshow_label.setText(f'{temp} c')
        self.pressureshow_label.setText(f'{pressure}')
        self.humidityshow_label.setText(f'{humidity}%')
        self.windshow_label.setText(f'{wind_speed} m/s')
        self.sunriseshow_label.setText(f'{sunrise}')
        self.sunsetshow_label.setText(f'{sunset}')
        self.visibility_label.setText(f'{visibility}')
        self.feelslike_label.setText(f'{feels_like}')
        self.lat_label.setText(f'{lat_coord}')
        self.lon_label.setText(f'{lon_coord}')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WeatherApp"))
        self.cityname_label.setText(_translate("MainWindow", "Enter City Name:"))
        self.mintemp_label.setText(_translate("MainWindow", "min temp"))
        self.maxtemp_label.setText(_translate("MainWindow", "max temp"))
        self.time_label.setText(_translate("MainWindow", "Time"))
        self.day_label.setText(_translate("MainWindow", "Day"))
        self.date_label.setText(_translate("MainWindow", "Date"))
        self.currenttime1_label.setText(_translate("MainWindow", "Current"))
        self.currenttime1_label_2.setText(_translate("MainWindow", "Date"))
        self.currenttime1_label_3.setText(_translate("MainWindow", "Time"))
        self.currenttime1_label_4.setText(_translate("MainWindow", "&"))
        self.description_label.setText(_translate("MainWindow", "Description"))
        self.tempreture_label.setText(_translate("MainWindow", "TEMPRETURE"))
        self.pressure_label.setText(_translate("MainWindow", "PRESSURE"))
        self.humidity_label.setText(_translate("MainWindow", "HUMIDITY"))
        self.currentweather_label.setText(_translate("MainWindow", "CURRENT WEATHER"))
        self.sindspeed_label.setText(_translate("MainWindow", "WIND SPEED"))
        self.sunset_label.setText(_translate("MainWindow", "SUNSET"))
        self.sunrise_label.setText(_translate("MainWindow", "SUNRISE"))
        self.visibility_label.setText(_translate("MainWindow", "visibility"))
        self.feelslike_label.setText(_translate("MainWindow", "feels like"))
        self.lat_label.setText(_translate("MainWindow", "lat"))
        self.lon_label.setText(_translate("MainWindow", "lon"))

#Initialize the app
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
